4.9.0

diff --git a/mailslurp b/mailslurp
--- a/mailslurp
+++ b/mailslurp
@@ -122,6 +122,8 @@ operation_parameters_minimum_occurrences["deleteWebhook:::inboxId"]=1
 operation_parameters_minimum_occurrences["deleteWebhook:::webhookId"]=1
 operation_parameters_minimum_occurrences["downloadAttachment:::attachmentId"]=1
 operation_parameters_minimum_occurrences["downloadAttachment:::emailId"]=1
+operation_parameters_minimum_occurrences["forwardEmail:::emailId"]=1
+operation_parameters_minimum_occurrences["forwardEmail:::ForwardEmailOptions"]=1
 operation_parameters_minimum_occurrences["getEmail:::emailId"]=1
 operation_parameters_minimum_occurrences["getEmails:::inboxId"]=1
 operation_parameters_minimum_occurrences["getEmails:::limit"]=0
@@ -172,6 +174,8 @@ operation_parameters_maximum_occurrences["deleteWebhook:::inboxId"]=0
 operation_parameters_maximum_occurrences["deleteWebhook:::webhookId"]=0
 operation_parameters_maximum_occurrences["downloadAttachment:::attachmentId"]=0
 operation_parameters_maximum_occurrences["downloadAttachment:::emailId"]=0
+operation_parameters_maximum_occurrences["forwardEmail:::emailId"]=0
+operation_parameters_maximum_occurrences["forwardEmail:::ForwardEmailOptions"]=0
 operation_parameters_maximum_occurrences["getEmail:::emailId"]=0
 operation_parameters_maximum_occurrences["getEmails:::inboxId"]=0
 operation_parameters_maximum_occurrences["getEmails:::limit"]=0
@@ -219,6 +223,8 @@ operation_parameters_collection_type["deleteWebhook:::inboxId"]=""
 operation_parameters_collection_type["deleteWebhook:::webhookId"]=""
 operation_parameters_collection_type["downloadAttachment:::attachmentId"]=""
 operation_parameters_collection_type["downloadAttachment:::emailId"]=""
+operation_parameters_collection_type["forwardEmail:::emailId"]=""
+operation_parameters_collection_type["forwardEmail:::ForwardEmailOptions"]=""
 operation_parameters_collection_type["getEmail:::emailId"]=""
 operation_parameters_collection_type["getEmails:::inboxId"]=""
 operation_parameters_collection_type["getEmails:::limit"]=""
@@ -638,6 +644,7 @@ read -r -d '' ops <<EOF
   ${CYAN}deleteInbox${OFF};Delete Inbox / Email Address (AUTH)
   ${CYAN}deleteWebhook${OFF};Delete and disable a WebHook for an Inbox (AUTH)
   ${CYAN}downloadAttachment${OFF};Get email attachment (AUTH)
+  ${CYAN}forwardEmail${OFF};Forward Email (AUTH)
   ${CYAN}getEmail${OFF};Get Email Content (AUTH)
   ${CYAN}getEmails${OFF};List Emails in an Inbox / EmailAddress (AUTH)
   ${CYAN}getInbox${OFF};Get Inbox / EmailAddress (AUTH)
@@ -1142,6 +1149,32 @@ print_downloadAttachment_help() {
     echo -e "${BOLD}${WHITE}Responses${OFF}"
     code=200
     echo -e "${result_color_table[${code:0:1}]}  200;OK${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+    code=401
+    echo -e "${result_color_table[${code:0:1}]}  401;Unauthorized${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+    code=403
+    echo -e "${result_color_table[${code:0:1}]}  403;Forbidden${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+    code=404
+    echo -e "${result_color_table[${code:0:1}]}  404;Not Found${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+}
+##############################################################################
+#
+# Print help for forwardEmail operation
+#
+##############################################################################
+print_forwardEmail_help() {
+    echo ""
+    echo -e "${BOLD}${WHITE}forwardEmail - Forward Email${OFF}${BLUE}(AUTH - HEADER)${OFF}" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo -e ""
+    echo -e "Forward email content to given recipients" | paste -sd' ' | fold -sw 80
+    echo -e ""
+    echo -e "${BOLD}${WHITE}Parameters${OFF}"
+    echo -e "  * ${GREEN}emailId${OFF} ${BLUE}[string]${OFF} ${RED}(required)${OFF} ${CYAN}(default: null)${OFF} - emailId ${YELLOW}Specify as: emailId=value${OFF}" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo -e "  * ${GREEN}body${OFF} ${BLUE}[application/json]${OFF} ${RED}(required)${OFF}${OFF} - forwardEmailOptions" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo -e ""
+    echo ""
+    echo -e "${BOLD}${WHITE}Responses${OFF}"
+    code=201
+    echo -e "${result_color_table[${code:0:1}]}  201;Created${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
     code=401
     echo -e "${result_color_table[${code:0:1}]}  401;Unauthorized${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
     code=403
@@ -2237,6 +2270,84 @@ call_downloadAttachment() {
 
 ##############################################################################
 #
+# Call forwardEmail operation
+#
+##############################################################################
+call_forwardEmail() {
+    # ignore error about 'path_parameter_names' being unused; passed by reference
+    # shellcheck disable=SC2034
+    local path_parameter_names=(emailId)
+    # ignore error about 'query_parameter_names' being unused; passed by reference
+    # shellcheck disable=SC2034
+    local query_parameter_names=(  )
+    local path
+
+    if ! path=$(build_request_path "/emails/{emailId}/forward" path_parameter_names query_parameter_names); then
+        ERROR_MSG=$path
+        exit 1
+    fi
+    local method="POST"
+    local headers_curl
+    headers_curl=$(header_arguments_to_curl)
+    if [[ -n $header_accept ]]; then
+        headers_curl="${headers_curl} -H 'Accept: ${header_accept}'"
+    fi
+
+    local basic_auth_option=""
+    if [[ -n $basic_auth_credential ]]; then
+        basic_auth_option="-u ${basic_auth_credential}"
+    fi
+    local body_json_curl=""
+
+    #
+    # Check if the user provided 'Content-type' headers in the
+    # command line. If not try to set them based on the OpenAPI specification
+    # if values produces and consumes are defined unambigously
+    #
+    if [[ -z $header_content_type ]]; then
+        header_content_type="application/json"
+    fi
+
+
+    if [[ -z $header_content_type && "$force" = false ]]; then
+        :
+        echo "ERROR: Request's content-type not specified!!!"
+        echo "This operation expects content-type in one of the following formats:"
+        echo -e "\\t- application/json"
+        echo ""
+        echo "Use '--content-type' to set proper content type"
+        exit 1
+    else
+        headers_curl="${headers_curl} -H 'Content-type: ${header_content_type}'"
+    fi
+
+
+    #
+    # If we have received some body content over pipe, pass it from the
+    # temporary file to cURL
+    #
+    if [[ -n $body_content_temp_file ]]; then
+        if [[ "$print_curl" = true ]]; then
+            echo "cat ${body_content_temp_file} | curl ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} \"${host}${path}\" -d @-"
+        else
+            eval "cat ${body_content_temp_file} | curl ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} \"${host}${path}\" -d @-"
+        fi
+        rm "${body_content_temp_file}"
+    #
+    # If not, try to build the content body from arguments KEY==VALUE and KEY:=VALUE
+    #
+    else
+        body_json_curl=$(body_parameters_to_json)
+        if [[ "$print_curl" = true ]]; then
+            echo "curl ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} ${body_json_curl} \"${host}${path}\""
+        else
+            eval "curl ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} ${body_json_curl} \"${host}${path}\""
+        fi
+    fi
+}
+
+##############################################################################
+#
 # Call getEmail operation
 #
 ##############################################################################
@@ -2794,6 +2905,9 @@ case $key in
     downloadAttachment)
     operation="downloadAttachment"
     ;;
+    forwardEmail)
+    operation="forwardEmail"
+    ;;
     getEmail)
     operation="getEmail"
     ;;
@@ -2958,6 +3072,9 @@ case $operation in
     ;;
     downloadAttachment)
     call_downloadAttachment
+    ;;
+    forwardEmail)
+    call_forwardEmail
     ;;
     getEmail)
     call_getEmail
